### ISSUE TITLE
可能有一个地方设计不协调

### ISSUE THREAD

**Issue by muddyneil** [datyin/theme-ocean-green#1]
约韦，你好！
我正在使用Ocean-green主题，这真是我最喜欢的主题了！这个配色，非常典雅而舒适。使用中我觉得有一处显示不大协调，如下图所示，在python中，self参数被加粗并斜体了，这让它过度显眼。this 和 self 被设计成加粗并斜体了，我觉得不需要突出显示这个参数，同其他参数一样显示就好了。
![Screenshot 2023-05-06](https://user-images.githubusercontent.com/35959703/236573069-5789223d-e1c8-4671-8120-ad9b129afe85.jpg)

还有一处颜色可能需要改进，如下图所示，C源代码中，#include 和 #define 显示颜色太暗了，眼睛看起来很费劲。
![Screenshot 2023-05-30](https://github.com/datyin/theme-ocean-green/assets/35959703/d4524e32-56ba-4c9e-aabc-50b2d2c647e3)

祝好！

**Comment by datyin** [comment]
Sorry for the late response. Both of them should be fixed now in version 1.1.0.
